- name: services directory
  ansible.builtin.file:
    path: /root/services/
    state: directory
    mode: '700'

- name: copy
  ansible.builtin.copy:
    src: nextcloud
    dest: /root/services/
    owner: root
    group: root
    mode: '700'

- name: run nextcloud
  ansible.builtin.shell: "cd /root/services/nextcloud && docker-compose down && docker-compose up -d"

- name: add backup nextcloud script to crontab
  ansible.builtin.cron:
    name: backup nextcloud
    minute: "06"
    hour: "2"
    user: root
    job: "/root/services/nextcloud/backup.sh > /dev/null 2>&1"

- name: add background jobs to cron
  ansible.builtin.cron:
    name: nextcloud background jobs
    minute: "*/5"
    hour: "*"
    user: root
    job: "docker exec --user www-data nextcloud.do-p.com php cron.php"
