http:
  routers:
    mail:
      rule: Host(`mail.do-p.com`)
      tls:
        certresolver:
          letsencrypt
      service: mail
      entryPoints:
        - https
      middlewares:
        - mail-whitelist

  middlewares:
    mail-whitelist:
      ipWhiteList:
        sourceRange:
          - "10.100.94.1/24"

  services:
    mail:
      loadBalancer:
        servers:
          - url: https://10.100.100.11
