- name: ensure iptables is started and enabled at boot
  ansible.builtin.systemd:
    name: iptables
    state: started
    enabled: yes

- name: iptables.rules
  ansible.builtin.copy:
    src: iptables.rules
    dest: /etc/iptables/iptables.rules
    owner: root
    group: root
    mode: '644'
    backup: yes
  notify: restart iptables
